name: Benchmark code

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.21"

      - name: Set up Python
        run: uv python install

      - name: Install packages
        run: uv sync

      - name: Run benchmark
        run: |
          hyperfine -L width 32,64,128,256,512 --warmup 3 'uv run scripts/run_finegrained.py --width {widt h}'

